
default: &default
  adapter: postgresql
  encoding: unicode
  user: vagner
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: agenda_api_development

test:
  <<: *default
  database: agenda_api_test

production:
  <<: *default
  database: agenda_api_production
  username: agenda_api
  password: <%= ENV['AGENDA_API_DATABASE_PASSWORD'] %>
